NewBlog/urls.py
from django.contrib import admin
from django.urls import path, include
from blog.feeds import AllPostsRssFeed

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace = 'blog')),
    path('', include('comments.urls', namespace = 'comments')),
    path('', include('contacts.urls', namespace = 'contacts')),
    path('all/rss/', AllPostsRssFeed(), name = 'rss'),
    path('search/', include('haystack.urls')),
]

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.IndexView.as_view(), name = 'index'),
    path('blog/', views.BlogsView.as_view(), name = 'blog'),
    path('post/<int:pk>/', views.PostPageView.as_view(), name = 'post_page'),
    path('archive/<int:year>/<int:month>/', views.ArchiveView.as_view(), name = 'archive'),
    path('category/<int:pk>/', views.CategoryView.as_view(), name = 'category'),
    path('tag/<int:pk>/', views.TagView.as_view(), name = 'tag'),
    path('about/', views.about_page, name = 'about'),
    path('contact/', views.contact_page, name = 'contact'),
    # path('search/', views.search, name = 'search'),


]

comments/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'comments'

urlpatterns = [
    path('comment/post/<int:post_id>/', views.post_comment, name = 'post_comment'),

]

contacts/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'contacts'

urlpatterns = [
    path('contact/post', views.contact_post, name = 'contact_post'),

]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils.html import strip_tags
import markdown


# Create your models here.

# class name represent table name in database
class Category(models.Model):
    name = models.CharField(max_length = 30)
    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField(max_length = 30)
    def __str__(self):
        return self.name


class Post(models.Model):
    title = models.CharField(default = 'Title', max_length = 200)
    content = models.TextField(null = True)
    create_time = models.DateTimeField(auto_now_add = True)
    modify_time = models.DateTimeField(auto_now = True)
    summary = models.CharField(max_length = 200, blank = True)
    category = models.ForeignKey(Category, on_delete = models.CASCADE)  # 级联
    tags = models.ManyToManyField(Tag, blank = True)
    author = models.ForeignKey(User, on_delete = models.CASCADE)
    views = models.PositiveIntegerField(default = 0, editable = False)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_page', kwargs = {'pk': self.pk})

    def increase_views(self):
        self.views += 1
        self.save(update_fields = ['views'])

    def save(self, *args, **kwargs):
        if not self.summary:
            md = markdown.Markdown(extensions = [
                'markdown.extensions.extra',
                'markdown.extensions.codehilite',
            ])
            self.summary = strip_tags(md.convert(self.content))[:70]

        super(Post, self).save(*args, **kwargs)

    class Meta:
        ordering = ['-create_time']

comments/models.py
from django.db import models

# Create your models here.
class Comment(models.Model):
    name = models.CharField(max_length = 30)
    email = models.EmailField(max_length = 100)
    url = models.URLField(blank = True)
    text = models.TextField()
    create_time = models.DateTimeField(auto_now_add = True)
    post = models.ForeignKey('blog.Post', on_delete = models.CASCADE)

    def __str__(self):
        return self.text[:20]

contacts/models.py
from django.db import models

# Create your models here.
class Contact(models.Model):
    name = models.CharField(max_length = 30)
    email = models.EmailField(max_length = 100)
    text = models.TextField()
    create_time = models.DateTimeField(auto_now_add = True)

comments/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'email', 'url', 'text']

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import Post, Category, Tag
from comments.forms import CommentForm
from django.views.generic import ListView, DetailView
from markdown.extensions.toc import TocExtension
from django.utils.text import slugify
from django.db.models import Q

import markdown


class IndexView(ListView):
    model = Post
    template_name = 'blog/index.html'
    context_object_name = 'posts'
    # paginate_by = 5

class BlogsView(ListView):
    model = Post
    template_name = 'blog/blog.html'
    context_object_name = 'posts'


class PostPageView(DetailView):
    model = Post
    template_name = 'blog/single.html'
    context_object_name = 'post'

    def get(self, request, *args, **kwargs):
        response = super(PostPageView, self).get(request, *args, **kwargs)
        self.object.increase_views()
        return response

    def get_object(self, queryset=None):
        post = super(PostPageView, self).get_object(queryset = None)
        md = markdown.Markdown(extensions = [
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
            TocExtension(slugify = slugify),
        ])
        post.content = md.convert(post.content)
        post.toc = md.toc
        return post

    def get_context_data(self, **kwargs):
        context = super(PostPageView, self).get_context_data(**kwargs)
        form = CommentForm()
        comment_list = self.object.comment_set.all()
        context.update({
            'form': form,
            'comment_list': comment_list,
        })
        return context


class ArchiveView(ListView):
    model = Post
    template_name = 'blog/blog.html'
    context_object_name = 'posts'

    def get_queryset(self):
        year = self.kwargs.get('year')
        month = self.kwargs.get('month')
        return super(ArchiveView, self).get_queryset().filter(create_time__year = year, create_time__month = month)


class CategoryView(ListView):
    model = Post
    template_name = 'blog/blog.html'
    context_object_name = 'posts'

    def get_queryset(self):
        cate = get_object_or_404(Category, pk = self.kwargs.get('pk'))
        return super(CategoryView, self).get_queryset().filter(category = cate)


class TagView(ListView):
    model = Post
    template_name = 'blog/blog.html'
    context_object_name = 'posts'

    def get_queryset(self):
        tag = get_object_or_404(Tag, pk = self.kwargs.get('pk'))
        return super(TagView, self).get_queryset().filter(tags = tag)


def about_page(request):
    return render(request, 'blog/about.html')


def contact_page(request):
    return render(request, 'blog/contact.html')

comments/views.py
from django.shortcuts import render, redirect, get_object_or_404
from blog.models import Post

from .models import Comment
from .forms import CommentForm

# Create your views here.
def post_comment(request, post_id):
    post = get_object_or_404(Post, pk = post_id)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit = False)
            comment.post = post
            comment.save()
            return redirect(post)
        else:
            comment_list = post.comment_set.all()
            dict = {'post': post, 'form': form, 'comment_list': comment_list}
            return render(request, 'blog/single.html', dict)
    else:
        return redirect(post)

contacts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Contact


# Create your views here.
def contact_post(request):
    if request.POST:
        name = request.POST['name']
        email = request.POST['email']
        text = request.POST['text']
        Contact.objects.create(name = name, email = email, text = text)

    return redirect('blog:contact')

blog/templates/base.html
{% load  staticfiles %}
{% load blog_tags %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Clara的博客</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="theme-color" content="#03a6f3">
    <link rel="stylesheet" href="{% static 'blog/css/bootstrap.min.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Old+Standard+TT:400,400i,700|Raleway:300,400,500,600,700" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'blog/css/custom.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/styles.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/mystyle.css' %}">

    <style>
        span.highlighted{
            color: red;
        }
    </style>

</head>

<body>
    <header>
        <div class="header-top"></div>
        <div>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <i class="fa fa-bars" aria-hidden="true"></i>
            </button>
            <div class="collapse navbar-collapse">
                <div class="nav-sec">
                    <div class="container">
                        <ul class="nav">
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'blog:index' %}">首页</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'blog:blog' %}">博客</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'blog:about' %}">关于</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'blog:contact' %}">联系</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="header-main">
            <div class="container">
                <div class="row">
                    <div class="col-md-4 align-self-center sharing-sec">
                    </div>
                    <div class="col-md-4 align-self-center">
                        <div class="logo-sec">
{#                            <img src="{% static 'blog/images/logo.png' %}" alt="logo">#}
                            <h1>Clara的博客</h1>
                        </div>
                    </div>
                    <div class="col-md-4 align-self-center">
                        <div class="search-sec">
                            <div class="search">
                                <form action="{% url 'haystack_search' %}" method="get">
                                    <input type="text" placeholder="搜索" name="q" required>
                                    <button type="submit"><span class="ion-ios-search-strong"></span></button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
                </div>
                </div>
    </header>

    <!-- Main body sec -->

    <section class="main-sec">
        <div class="container">
            <div class="standard-post-format">
                {% block main %}
                {% endblock %}
            </div>
            <div class="tlinks">Collect from <a href="http://www.cssmoban.com/" >网站建设</a></div>

            <!-- Aside section start -->
            <aside>
                {% block toc %}
                {% endblock toc %}
                <div class="category-sec">
                    <h3 class="category">分类</h3>
                    {% get_categories as category_list %}
                    <ul>
                        {% for category in category_list %}
                        <li>
                            <a href="{% url 'blog:category' category.pk %}" class="active">{{ category.name }}</a>
                        </li>
                        {% empty %}
                        暂无分类！
                        {% endfor %}
                    </ul>
                </div>

                <div class="category-sec">
                    <h3 class="archive">归档</h3>
                    {% archives as date_list %}
                    <ul>
                        {% for date in date_list %}
                        <li>
                            <a href="{% url 'blog:archive' date.year date.month %}" class="active">{{ date.year }} 年 {{ date.month }} 月</a>
                        </li>
                        {% empty %}
                        暂无归档！
                        {% endfor %}
                    </ul>
                </div>
                <div class="most-read">
                    <h3 class="mostread">最多浏览</h3>
                    {% get_most_read_posts as most_read_post_list %}
                    <ul>
                        {% for post in most_read_post_list %}
                            <li>
                                <figure style="background:url({% static 'blog/images/rsmall.jpg' %})no-repeat;"></figure>
                                <div class="post-content">
                                    <h3><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h3>
                                    <h5>{{ post.create_time }}</h5>
                                    <span>By <a href="#">{{ post.author }}</a></span>
                                    <span>阅读 <a href="#">{{ post.views }}</a></span>
                                </div>
                            </li>
                            {% empty %}
                            暂无文章！
                        {% endfor %}
                    </ul>
                </div>
<!-- Tag section -->
                <div class="tag-sec">
                    <h3 class="tags">标签云</h3>
                    {% get_tags as tag_list %}
                    <ul>
                        {% for tag in tag_list %}
                            <li>
                                <a href="{% url 'blog:tag' tag.pk %}" >{{ tag.name }}</a>
                            </li>
                            {% empty %}
                            暂无标签！
                        {% endfor %}
                    </ul>
                </div>

                <div class="rss" align="center">
                    <a href="{% url 'rss' %}"><span class="ion-social-rss-outline"></span> RSS 订阅</a>
                </div>
            </aside>
        </div>
    </section>

    <footer>
        <div class="container">
            <h5>(C) 2019. All Rights Reserved. Clara的博客</h5>
        </div>
    </footer>
    <script src="js/jquery.min.js"></script>
    <script src="js/bootstrap.min.js"></script>
    <script src="js/custom.js"></script>

</body>

</html>

blog/templates/blog/about.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block main %}
    <div class="row">
        <div class="col-md-12">
            <div class="post-item big-post">
                <h1 class="post-title">关于</h1>
                <img src="{% static 'blog/images/post1.jpg' %}" alt="post-img">

                    <p>
                    欢迎来到我的博客！这个博客使用HTML5和CSS编写的网页作为前端，后台用Python和Django实现，数据库是MySQL。<br/><br/>
                    对实现感兴趣的同学可以访问该项目的github链接: <a href="https://github.com/CLaraRR/MyBlog" target="_blank">https://github.com/CLaraRR/MyBlog</a><br/><br/>
                    我的github: <a href="https://github.com/CLaraRR" target="_blank">https://github.com/CLaraRR</a><br/><br/>
                    我的CSDN博客：<a href="https://blog.csdn.net/qq_33648725" target="_blank">https://blog.csdn.net/qq_33648725</a><br/><br/>
                    </p>

            </div>
        </div>
    </div>
{% endblock main %}

blog/templates/blog/blog.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block main %}
    {% if posts.count == 1 %}
        <div class="row">
            <div class="col-md-12">
                <!-- Big post section -->
{#                {% for post in posts %}#}

                <div class="post-item big-post">
                    <h2 class="post-title"><a href="{{ posts.0.get_absolute_url }}" class="post-title">{{ posts.0.title }}</a></h2>
                    <img src="{% static 'blog/images/post1.jpg' %}" alt="post-img">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item">{{ posts.0.create_time }}</li>
                        <li class="breadcrumb-item"> By <a href="#" class="admin">{{ posts.0.author }}</a></li>
                        <li class="breadcrumb-item">In <a href="#" class="fashion">{{ posts.0.category }} </a></li>
                        <li class="breadcrumb-item">({{ posts.0.comment_set.count }}) <a href="{{ posts.0.get_absolute_url }}#comment-list">评论</a></li>
                        <li class="breadcrumb-item">({{ posts.0.views }}) <a href="{{ posts.0.get_absolute_url }}">阅读</a></li>
                    </ol>
                    <h5>{{ posts.0.summary }}</h5>
                    <a href="{{ posts.0.get_absolute_url }}" class="continue-read">继续阅读</a>
                </div>
{#                {% endfor %}#}
                <!-- End Big post section -->
            </div>
        </div>
    {% else %}
        <div class="row small-post-sec">
            {% for post in posts %}
                <div class="col-md-6 col-sm-6">
                    <div class="post-item small-post">
                        <img src="{% static 'blog/images/spost2.jpg' %}" alt="post-img">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item">{{ post.create_time }}</li>
                            <li class="breadcrumb-item"> By <a href="#" class="">{{ post.author }}</a></li>
                        </ol>
                        <h2><a href="{{ post.get_absolute_url }}" class="post-title">{{ post.title }}</a></h2>
                        <h5>
                            {{ post.summary }}
                    </h5>
                        <a href="{{ post.get_absolute_url }}" class="continue-read">继续阅读</a>
                    </div>
                </div>
                {% empty %}
                暂无文章！
            {% endfor %}
        </div>
    {% endif %}
{% endblock main %}

blog/templates/blog/contact.html
{% extends 'base.html' %}

{% block main %}
    <div class="row">
        <div class="col-md-12">
          <div class="contct-sec">
              <h1 class="post-title">联系</h1>
              <h6>如果您对我的博客有任何意见或建议，可以填写在下方表格</h6>

              <div class="form">
                <form action="{% url 'contacts:contact_post' %}" method="post">
                  {% csrf_token %}
                  <ul>
                      <li>
                          <input type="text" name="name" placeholder="名字" required>
                      </li>
                      <li>
                          <input type="email" placeholder="电子邮件" name="email" required>
                      </li>
                      <li>
                         <textarea type="text" placeholder="意见/建议" name="text" required></textarea>
                      </li>
                      <li>
                        <input type="submit" class="btn submit-btn" value="OK，我要提交">
                      </li>
                  </ul>
                </form>
              </div>
          </div>
        </div>
    </div>
{% endblock main %}

blog/templates/blog/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load blog_tags %}

{% block main %}
    <div class="row">
        <div class="col-md-12">
            <!-- Big post section -->
            {% get_recent_post as recent_post %}
            {% for post in recent_post %}
            <div class="post-item big-post">

                <h2 class="post-title">Latest: <a href="{{ post.get_absolute_url }}" class="post-title">{{ post.title }}</a></h2>
                <ol class="breadcrumb">
                    <li class="breadcrumb-item">{{ post.create_time }}</li>
                    <li class="breadcrumb-item"> By <a href="#" class="admin">{{ post.author }}</a></li>
                    <li class="breadcrumb-item">In <a href="#" class="fashion">{{ post.category }} </a></li>
                    <li class="breadcrumb-item">({{ post.comment_set.count }}) <a href="{{ post.get_absolute_url }}#comment-list">评论</a></li>
                    <li class="breadcrumb-item">({{ post.views }}) <a href="{{ post.get_absolute_url }}">阅读</a></li>
                </ol>
                <h5>{{ post.summary }}</h5>
                <a href="{{ post.get_absolute_url }}" class="continue-read">继续阅读</a>
            </div>
            {% endfor %}
            <!-- End Big post section -->
        </div>
    </div>


    <div class="row small-post-sec">
        {% for post in posts %}
            <div class="col-md-6 col-sm-6">
                <div class="post-item small-post">
                    <h2 class="post-title-h2"><a href="{{ post.get_absolute_url }}" >{{ post.title }}</a></h2>
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item">{{ post.create_time }}</li>
                        <li class="breadcrumb-item"> By <a href="#" class="">{{ post.author }}</a></li>
                    </ol>
                    <h5>
                        {{ post.summary }}
                </h5>
                    <a href="{{ post.get_absolute_url }}" class="continue-read">继续阅读</a>
                </div>
            </div>
            {% empty %}
            暂无文章！
        {% endfor %}
    </div>
    <div class="button-sec">
        <button class="btn load-more">load more</button>
    </div>
{% endblock %}

blog/templates/blog/single.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block main %}
    <div class="row">
        <div class="col-md-12">
            <div class="post-item big-post">
                <h1 class="post-title"><a href="{{ post.get_absolute_url }}" class="post-title">{{ post.title }}</a></h1>
                <ol class="breadcrumb">
                    <li class="breadcrumb-item">{{ post.create_time }}</li>
                    <li class="breadcrumb-item"> By <a href="#" class="admin">{{ post.author }}</a></li>
                    <li class="breadcrumb-item">In <a href="#" class="fashion">{{ post.category }} </a></li>
                    <li class="breadcrumb-item">({{ post.comment_set.count }}) <a href="{{ post.get_absolute_url }}#comment-list">评论</a></li>
                    <li class="breadcrumb-item">({{ post.views }}) <a href="{{ post.get_absolute_url }}">阅读</a></li>
                </ol>
                <p>{{ post.content|safe }}</p>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="comment-area" id="comment-list">
                <h1><a>发表评论</a></h1>
                <form action="{% url 'comments:post_comment' post.id %}" method="post" class="comment-form">
                {% csrf_token %}
                <div class="row">
                    <div class="col-md-4">
                        <label for="{{ form.name.id_for_label }}">名字：</label>
                        {{ form.name }}
                        {{ form.name.errors }}
                    </div>
                    <div class="col-md-4">
                        <label for="{{ form.email.id_for_label }}">邮箱：</label>
                        {{ form.email }}
                        {{ form.email.errors }}
                    </div>
                    <div class="col-md-4">
                        <label for="{{ form.url.id_for_label }}">网址：</label>
                        {{ form.url }}
                        {{ form.url.errors }}
                    </div>
                    <div class="col-md-12">
                        <label for="{{ form.text.id_for_label }}">评论：</label>
                        {{ form.text }}
                        {{ form.text.errors }}
                        <button type="submit" class="comment-btn">发表</button>
                    </div>
                </div>    <!-- row -->
                </form>
            </div>
        </div>
    </div>
    <br/><br/><br/>
    <div class="row">
        <div class="col-md-12">
            <div class="comment-area" >
                <h1><a>评论列表，共 <span>{{ post.comment_set.count }}</span> 条评论</a></h1>
                <ul class="comment-list list-unstyled">
                    {% for comment in comment_list %}
                        <li class="comment-item">
                            <span class="nickname">{{ comment.name }}</span>
                            <time class="submit-date" datetime="{{ comment.create_time }}">{{ comment.create_time }}</time>
                            <div class="text">
                                {{ comment.text }}
                            </div>
                        </li>
                    {% empty %}
                        暂无评论！
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>

{% endblock main %}

{% block toc %}
    <div class="category-sec">
        <h3 class="toc">文章目录</h3>
        {{ post.toc|safe }}
    </div>
{% endblock toc %}

blog/templates/search/search.html
{% extends 'base.html' %}
{% load highlight %}
{% load staticfiles %}

{% block main %}
    {% if query %}
        <div class="row">
        <div class="col-md-12">
            <!-- Big post section -->
            {% for result in page.object_list %}
            <div class="post-item big-post">

                <h2 class="post-title"><a href="{{ result.object.get_absolute_url }}" class="post-title">{{ result.object.title }}</a></h2>
                <ol class="breadcrumb">
                    <li class="breadcrumb-item">{{ result.object.create_time }}</li>
                    <li class="breadcrumb-item"> By <a href="#" class="admin">{{ result.object.author }}</a></li>
                    <li class="breadcrumb-item">In <a href="#" class="fashion">{{ result.object.category }} </a></li>
                    <li class="breadcrumb-item">({{ result.object.comment_set.count }}) <a href="{{ result.object.get_absolute_url }}#comment-list">评论</a></li>
                    <li class="breadcrumb-item">({{ result.object.views }}) <a href="{{ result.object.get_absolute_url }}">阅读</a></li>
                </ol>
                <h5>
                    {% highlight result.object.content with query %}
                </h5>
                <a href="{{ result.object.get_absolute_url }}" class="continue-read">继续阅读</a>
            </div>
            {% empty %}
                没有搜索到你想要的结果！
            {% endfor %}
            <!-- End Big post section -->
        </div>
    </div>
    {% endif %}
{% endblock main %}